# Generated by Django 2.2.5 on 2019-09-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedetails',
            fields=[
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_password', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'employeedetails',
            },
        ),
        migrations.CreateModel(
            name='employee_educationaldetails',
            fields=[
                ('tenth_schoolname', models.CharField(blank=True, max_length=20)),
                ('tenth_schoolboard', models.CharField(blank=True, max_length=20)),
                ('tenth_percentage', models.CharField(blank=True, max_length=3)),
                ('tenth_cerificate', models.FileField(blank=True, upload_to='')),
                ('inter_collegename', models.CharField(blank=True, max_length=20)),
                ('inter_board', models.CharField(blank=True, max_length=20)),
                ('inter_percentage', models.CharField(blank=True, max_length=3)),
                ('inter_cerificate', models.FileField(blank=True, upload_to='')),
                ('graduation_collegename', models.CharField(blank=True, max_length=20)),
                ('graduation_board', models.CharField(blank=True, max_length=20)),
                ('graduation_percentage', models.CharField(blank=True, max_length=3)),
                ('graduation_cerificate', models.FileField(blank=True, upload_to='')),
                ('postgraduation_collegename', models.CharField(blank=True, max_length=20)),
                ('postgraduation_board', models.CharField(blank=True, max_length=20)),
                ('postgraduation_percentage', models.CharField(blank=True, max_length=3)),
                ('postgraduation_cerificate', models.FileField(blank=True, upload_to='')),
                ('is_post_graduationcertificate_uploaded', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'education_details',
            },
        ),
        migrations.CreateModel(
            name='weeklyactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=9, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Yes', 'yes'), ('No', 'no')], default='', max_length=6, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'weeklyacitivies',
            },
        ),
        migrations.CreateModel(
            name='employee_personaldetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_image', models.ImageField(upload_to='')),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('empoyee_dob', models.DateField()),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'Others')], default='Male', max_length=20)),
                ('maritial_status', models.CharField(max_length=15)),
                ('spouse_name', models.CharField(blank=True, max_length=15, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('aadhar_number', models.BigIntegerField()),
                ('upload_aadhar', models.FileField(upload_to='')),
                ('pan_number', models.CharField(max_length=15)),
                ('upload_pancard', models.FileField(upload_to='')),
                ('passport_number', models.CharField(blank=True, max_length=15, null=True)),
                ('drivinglicense_number', models.CharField(blank=True, max_length=20, null=True)),
                ('upload_drivinglicense', models.FileField(blank=True, null=True, upload_to='')),
                ('is_drivinglicense_uploaded', models.BooleanField(default=False)),
                ('upload_passport', models.FileField(blank=True, null=True, upload_to='')),
                ('is_passport_uploaded', models.BooleanField(default=False)),
                ('voter_id_number', models.CharField(blank=True, max_length=15, null=True)),
                ('upload_voterid', models.FileField(blank=True, null=True, upload_to='')),
                ('is_Voterid_uploaded', models.BooleanField(default=False)),
                ('Address1', models.CharField(max_length=300)),
                ('Address2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('postal_code', models.IntegerField(null=True)),
                ('telephone', models.BigIntegerField(blank=True, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('relatives_name', models.CharField(max_length=15)),
                ('relation', models.CharField(blank=True, max_length=15, null=True)),
                ('relative_address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('relative_mobile_number', models.BigIntegerField(null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'personal_details',
            },
        ),
        migrations.CreateModel(
            name='employee_experiencedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organisation', models.CharField(max_length=30)),
                ('job_role', models.CharField(max_length=20)),
                ('period_of_work', models.CharField(max_length=20)),
                ('package', models.BigIntegerField(null=True)),
                ('total_experience', models.CharField(max_length=20)),
                ('forms_any', models.FileField(blank=True, null=True, upload_to='')),
                ('is_form_any_uploaded', models.BooleanField(default=False)),
                ('relieving_letter', models.FileField(upload_to='')),
                ('pay_slip', models.FileField(upload_to='')),
                ('name_of_organisation1', models.CharField(max_length=30, null=True)),
                ('job_role1', models.CharField(max_length=20, null=True)),
                ('period_of_work1', models.CharField(max_length=20, null=True)),
                ('package1', models.BigIntegerField(null=True)),
                ('total_experience1', models.CharField(blank=True, max_length=20, null=True)),
                ('forms_any1', models.FileField(blank=True, null=True, upload_to='')),
                ('is_form_any_uploaded1', models.BooleanField(default=False)),
                ('relieving_letter1', models.FileField(blank=True, null=True, upload_to='')),
                ('is_relivingletter_uploaded', models.BooleanField(default=False)),
                ('pay_slip1', models.FileField(null=True, upload_to='')),
                ('is_pay_slip1', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'experience_details',
            },
        ),
        migrations.CreateModel(
            name='employee_attendance',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateField(blank=True)),
                ('login_time', models.TimeField(auto_now_add=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='applied_leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick_leave', 'Sick_Leave'), ('casual_leave', 'Casual_Leave')], default='casual_leave', max_length=20)),
                ('reason', models.CharField(max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_days', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pndg'), ('sactioned', 'yes'), ('rejected', 'no')], default='pending', max_length=10)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetails')),
            ],
            options={
                'db_table': 'applied_leaves',
            },
        ),
    ]
